### ISSUE TITLE
Crash on starting up on server 1.20.1 Fabric

### ISSUE THREAD

**Issue by NantaArthur123** [TheWinABagel/Zenith#118]
```
[09:59:31] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'zenith'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.NoClassDefFoundError: io/github/fabricators_of_create/porting_lib/entity/events/living/LivingEntityLootEvents
        at dev.shadowsoffire.apotheosis.spawn.SpawnerModule.dropsEvent(SpawnerModule.java:61) ~[zenith-1.0.6-1.20.1.jar:?]
        at dev.shadowsoffire.apotheosis.spawn.SpawnerModule.init(SpawnerModule.java:46) ~[zenith-1.0.6-1.20.1.jar:?]
        at dev.shadowsoffire.apotheosis.Apotheosis.onInitialize(Apotheosis.java:42) ~[zenith-1.0.6-1.20.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.entity.events.living.LivingEntityLootEvents
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at dev.shadowsoffire.apotheosis.spawn.SpawnerModule.dropsEvent(SpawnerModule.java:61) ~[zenith-1.0.6-1.20.1.jar:?]
        at dev.shadowsoffire.apotheosis.spawn.SpawnerModule.init(SpawnerModule.java:46) ~[zenith-1.0.6-1.20.1.jar:?]
        at dev.shadowsoffire.apotheosis.Apotheosis.onInitialize(Apotheosis.java:42) ~[zenith-1.0.6-1.20.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
        ... 6 more
```

this is the logs
https://mclo.gs/u7uxBzP

**Comment by TeslaP09** [comment]
I had that too when I updated Zenith Attributes to 0.2.0 and FakerLib to 0.1.3, because I still had an old zenith version with mismatching porting libs. You also need the new zenith version (1.1.0) with the new porting lib, which is currently only available on CurseForge. I see that you still have zenith-1.0.6-1.20.1 installed, so that might be the problem :)

**Comment by NantaArthur123** [comment]
ohh thank you for the reply I will try it

**Comment by TheWinABagel** [comment]
That should be the problem yeah, gotta update both :)

**Comment by NantaArthur123** [comment]
Sorry just got back from work
now I got this error
```
A potential solution has been determined, this may resolve your problem:
         - Replace mod 'Zenith Attributes' (zenith_attributes) 0.2.0 with version 0.2.0.1 or later.
More details:
         - Mod 'Zenith' (zenith) 1.1.0-1.20.1 requires version 0.2.0.1 or later of mod 'Zenith Attributes' (zenith_attributes), but only the wrong version is present: 0.2.0!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
```

while on curseforge and modrinth version 0.2.0.1 is not exist, am I missing something?

**Comment by TheWinABagel** [comment]
Update to zenith 1.1.1, I accidentally left the wrong version in the release
