### ISSUE TITLE
Anvil not working at all (bug)

### ISSUE THREAD

**Issue by TeslaP09** [TheWinABagel/Zenith#15]
Version: 1.19.2
Mod loader: Fabric
Mod version: 0.5.5

I have encountered a bug with this mod (yes, I have isolated the mod): With the enchanting module enabled, I cannot use the anvil, because the ui closes again immediately after interacting with the anvil. The enchanting table and stuff is working fine though. If I then decide to disable the enchanting module and restart the game, the moment I even just place an anvil, the game instantly saves and crashes. So in short, it is not possible for me to use the anvil in any way with this mod installed. 

Here's the crash report, just in case: 

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-04-22 23:40:27
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at safro.zenith.ench.anvil.AnvilBlockEntity.<init>(AnvilBlockEntity.java:26)
	at net.minecraft.class_2199.method_10123(class_2199.java:564)
	at net.minecraft.class_2818.method_12010(class_2818.java:268)
	at net.minecraft.class_1937.method_30092(class_1937.java:221)
	at net.minecraft.class_638.method_30092(class_638.java:156)
	at net.minecraft.class_1937.method_8652(class_1937.java:206)
	at net.minecraft.class_1747.method_7708(class_1747.java:159)
	at net.minecraft.class_1747.method_7712(class_1747.java:76)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_636.method_41934(class_636.java:363)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.method_1508(class_310.java:2002)
	at net.minecraft.class_310.method_1574(class_310.java:1829)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Attempted to register a recipe type after the registration period closed.
	at safro.zenith.util.ApotheosisUtil.makeRecipeType(ApotheosisUtil.java:146)
	at safro.zenith.ench.EnchModule.<clinit>(EnchModule.java:74)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at safro.zenith.ench.anvil.AnvilBlockEntity.<init>(AnvilBlockEntity.java:26)
	at net.minecraft.class_2199.method_10123(class_2199.java:564)
	at net.minecraft.class_2818.method_12010(class_2818.java:268)
	at net.minecraft.class_1937.method_30092(class_1937.java:221)
	at net.minecraft.class_638.method_30092(class_638.java:156)
	at net.minecraft.class_1937.method_8652(class_1937.java:206)
	at net.minecraft.class_1747.method_7708(class_1747.java:159)
	at net.minecraft.class_1747.method_7712(class_1747.java:76)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:264)
	at net.minecraft.class_636.method_41934(class_636.java:363)
	at net.minecraft.class_636.method_41933(class_636.java:328)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:327)
	at net.minecraft.class_310.method_1583(class_310.java:1748)
	at net.minecraft.class_310.method_1508(class_310.java:2002)

-- Affected level --
Details:
	All players: 1 total; [class_746['Tesla_P09'/262, l='ClientLevel', x=7.88, y=94.29, z=-25.48]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,75,-16), Section: (at 0,11,0 in 1,4,-1; chunk contains blocks 16,-64,-16 to 31,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 835 game time, 835 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1538754272 bytes (1467 MiB) / 3581935616 bytes (3416 MiB) up to 17146314752 bytes (16352 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3168
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 4.00
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 4.00
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 74972.30
	Virtual memory used (MB): 19076.03
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 58.01
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16352m -Xms256m
	Fabric Mods: 
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.19
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		zenith: Zenith 0.5.5+1.19.2
			porting_lib: Porting Lib 2.1.815+1.19.2
				com_github_llamalad7_mixinextras: MixinExtras 0.1.1
				forge_tags: Porting Lib Tags 3.0
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 2.1.815+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.815+1.19.2
				porting_lib_base: Porting Lib Base 2.1.815+1.19.2
				porting_lib_common: Porting Lib Common 2.1.815+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.815+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.815+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.815+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.815+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.815+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.815+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.815+1.19.2
				porting_lib_models: Porting Lib Models 2.1.815+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.815+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.815+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.815+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
	Launched Version: fabric-loader-0.14.19-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.68, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 24x 12th Gen Intel(R) Core(TM) i9-12900K
	Server Running: true
	Player Count: 1 / 8; [class_3222['Tesla_P09'/262, l='ServerLevel[Zenith test]', x=7.88, y=94.29, z=-25.48]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable

**Comment by TeslaP09** [comment]
I have downloaded and built the latest github version and the issue seems to be fixed with the merge request #12 so I will close this issue.
