### ISSUE TITLE
Crash When Reforging Items with Enchantments

### ISSUE THREAD

**Issue by Fablesider** [TheWinABagel/Zenith#201]
Minecraft crashes when attempting to reforge an enchanted tool or armor piece. The crash happens after placing a piece of enchanted gear into the reforging table and the UI animation has nearly completed. The reforging options are not shown. This bug seems to be an incompatibility issue with the Sodium mod.

Error Message: 
The game crashed whilst rendering screen
Error: java.lang.IllegalArgumentException: The class dev.shadowsoffire.apotheosis.adventure.client.GhostVertexBuilder does not implement interface VertexBufferWriter, which is required for compatibility with Sodium (see: https://github.com/CaffeineMC/sodium-fabric/issues/1620)

Exit Code: -1

Crash report: 

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-08-06 15:34:51
Description: Rendering screen

java.lang.IllegalArgumentException: The class dev.shadowsoffire.apotheosis.adventure.client.GhostVertexBuilder does not implement interface VertexBufferWriter, which is required for compatibility with Sodium (see: https://github.com/CaffeineMC/sodium-fabric/issues/1620)
	at net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.createUnsupportedVertexConsumerThrowable(VertexBufferWriter.java:46)
	at net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.of(VertexBufferWriter.java:22)
	at net.minecraft.class_4720$class_4589.push(class_4720.java:525)
	at net.coderbot.iris.compat.sodium.impl.vertex_format.entity_xhfp.EntityVertex.writeQuadVertices(EntityVertex.java:133)
	at me.jellysquid.mods.sodium.client.render.immediate.model.BakedModelEncoder.handler$clg000$iris$redirect2(BakedModelEncoder.java:531)
	at me.jellysquid.mods.sodium.client.render.immediate.model.BakedModelEncoder.writeQuadVertices(BakedModelEncoder.java)
	at net.minecraft.class_918.renderBakedItemQuads(class_918.java:3096)
	at net.minecraft.class_918.handler$dfi000$sodium$renderModelFast(class_918.java:3074)
	at net.minecraft.class_918.method_23182(class_918.java)
	at net.minecraft.class_918.method_23179(class_918.java:164)
	at dev.shadowsoffire.apotheosis.adventure.affix.salvaging.SalvagingScreen.renderGuiItem(SalvagingScreen.java:155)
	at dev.shadowsoffire.apotheosis.adventure.affix.reforging.ReforgingScreen.method_2385(ReforgingScreen.java:197)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at dev.shadowsoffire.placebo.screen.PlaceboContainerScreen.method_25394(PlaceboContainerScreen.java:19)
	at dev.shadowsoffire.apotheosis.adventure.affix.reforging.ReforgingScreen.method_25394(ReforgingScreen.java:48)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.createUnsupportedVertexConsumerThrowable(VertexBufferWriter.java:46)
	at net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.of(VertexBufferWriter.java:22)
	at net.minecraft.class_4720$class_4589.push(class_4720.java:525)
	at net.coderbot.iris.compat.sodium.impl.vertex_format.entity_xhfp.EntityVertex.writeQuadVertices(EntityVertex.java:133)
	at me.jellysquid.mods.sodium.client.render.immediate.model.BakedModelEncoder.handler$clg000$iris$redirect2(BakedModelEncoder.java:531)
	at me.jellysquid.mods.sodium.client.render.immediate.model.BakedModelEncoder.writeQuadVertices(BakedModelEncoder.java)
	at net.minecraft.class_918.renderBakedItemQuads(class_918.java:3096)
	at net.minecraft.class_918.handler$dfi000$sodium$renderModelFast(class_918.java:3074)
	at net.minecraft.class_918.method_23182(class_918.java)
	at net.minecraft.class_918.method_23179(class_918.java:164)
	at dev.shadowsoffire.apotheosis.adventure.affix.salvaging.SalvagingScreen.renderGuiItem(SalvagingScreen.java:155)
	at dev.shadowsoffire.apotheosis.adventure.affix.reforging.ReforgingScreen.method_2385(ReforgingScreen.java:197)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at dev.shadowsoffire.placebo.screen.PlaceboContainerScreen.method_25394(PlaceboContainerScreen.java:19)
	at dev.shadowsoffire.apotheosis.adventure.affix.reforging.ReforgingScreen.method_25394(ReforgingScreen.java:48)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: dev.shadowsoffire.apotheosis.adventure.affix.reforging.ReforgingScreen
	Mouse location: Scaled: (243, 74). Absolute: (972.000000, 299.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Fablesider'/230, l='ClientWorld minecraft:overworld', x=15.11, y=102.01, z=65.36]]
	Chunk stats: Client Chunks (ImmPtl) 1369
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,100,80), Section: (at 0,4,0 in 1,6,5; chunk contains blocks 16,-64,80 to 31,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 6170 game time, 6170 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/NoPumpkinBlur-rv1.3.zip, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1906483168 bytes (1818 MiB) / 4093640704 bytes (3904 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5123
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34462.96
	Virtual memory used (MB): 30245.88
	Swap memory total (MB): 18144.62
	Swap memory used (MB): 2846.62
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		balm-fabric: Balm 7.3.6
			kuma_api: KumaAPI 20.1.8
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		betterend: Better End 4.0.11
		betternether: Better Nether 9.0.10
		croptopia: Croptopia 3.0.3
		epherolib: EpheroLib 1.2.0
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fakerlib: fakerlib 0.1.4
			mixinsquared: MixinSquared 0.1.1
		geckolib: GeckoLib 4 4.4.7
			com_eliotlash_mclib_mclib: mclib 20
		graveyard: The Graveyard 3.0
		immersive_portals: Immersive Portals 3.3.7
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
			imm_ptl_core: Immersive Portals Core 3.3.7
			q_misc_util: QMiscUtil 3.3.7
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.8.2.25
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		naturalist: Naturalist 4.0.3
		patchouli: Patchouli 1.20.1-81-FABRIC
			fiber: fiber 0.23.0-2
		repurposed_structures: Repurposed Structures 7.1.15+1.20.1-fabric
		sodium: Sodium 0.5.3
		waystones: Waystones 14.1.4
		zenith: Zenith 1.2.2-1.20.1
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
				porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
				porting_lib_config: Porting Lib Config 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
		zenith_attributes: Zenith Attributes 0.2.6
			additionalentityattributes: Additional Entity Attributes 1.7.3+1.20.0
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			playerabilitylib: Pal 1.8.0
			porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
			porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
	Loaded Shaderpack: MakeUp-UltraFast-9.0.zip
		Profile: low (+0 options changed by user)
	Launched Version: fabric-loader-0.15.11-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.23, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/NoPumpkinBlur-rv1.3.zip (incompatible), fabric
	Current Language: en_us
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Fablesider'/230, l='ServerWorld minecraft:overworld testing', x=15.11, y=102.01, z=65.36]]
	Data Packs: vanilla, fabric, zenith:structures
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental

**Comment by Thelm76** [comment]
You'll need to update sodium to the latest version it seems to work better. 
I had the same crash, but now it is working properly

**Comment by Fablesider** [comment]
> You'll need to update sodium to the latest version it seems to work better. I had the same crash, but now it is working properly

Thank you, it works as normal with the latest version of sodium.
