### ISSUE TITLE
Spawner modifiers are not saved

### ISSUE THREAD

**Issue by Drakkar666** [TheWinABagel/Zenith#22]
I'm not a modder so above statement is probably wrong. Nonetheless whenever I place a Blaze Spawner in creative mode (copied from a Nether Fortress), I get the following error:

`[18:28:46] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_10577(String)" because "tag" is null
	at safro.zenith.spawn.spawner.ZenithSpawnerBlockEntity.method_11014(ZenithSpawnerBlockEntity.java:52) ~[zenith-0.5.7+1.19.2.jar:?]
	at safro.zenith.spawn.spawner.ZenithSpawnerBlockEntity.onDataPacket(ZenithSpawnerBlockEntity.java:74) ~[zenith-0.5.7+1.19.2.jar:?]
	at net.minecraft.class_634.handler$zfc000$porting_lib_base$port_lib$handleCustomBlockEntity(class_634.java:3501) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38542(class_634.java) ~[client-intermediary.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.class_634.method_11094(class_634.java:1135) ~[client-intermediary.jar:?]
	at net.minecraft.class_2622.method_11292(class_2622.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_2622.method_11054(class_2622.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

Getting far enough to unload the chunk or save & reopen results in the placed spawner forgetting it's modifiers.
Changing the mob spawned via spawn eggs does work.

OS: Kubuntu 22.04
Launcher: MultiMC
Fabric loader version: 0.14.19

Mods used:
* Fabric API 0.76.0+1.19.2
* Zenith 0.5.7+1.19.2
	
I have tried doing the same procedure with all other dependencies installed (REI, Patchouli, Enchantment Descriptions) and results are the same.

**Comment by TheWinABagel** [comment]
Spawner module is still a bit of a mess, I started cleanup but it has been slow as I've been quite busy the last few weeks, and I most likely will continue to be busy as school is getting a bit crazy. 
If you're in desperate need of a working spawner module, you can install [Apogee](https://www.curseforge.com/minecraft/mc-mods/apogee), but they aren't compatible with each other (you'd have to disable the spawner module)

**Comment by TheWinABagel** [comment]
Fixed as of 410c7e2b6811e8ab259963e4ad9770099b0545d5 as there was a rewrite of the spawner module
