### ISSUE TITLE
Dependency is not included

### ISSUE THREAD

**Issue by SiverDX** [TheWinABagel/Zenith#41]
Version: zenith-0.6.7+1.19.2.jar

``` log
[10:22:78] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: io/github/tropheusj/serialization_hooks/ingredient/IngredientDeserializer
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: io/github/tropheusj/serialization_hooks/ingredient/IngredientDeserializer
	at net.minecraft.class_1309.handler$ccp000$createAttributes(class_1309.java:20292)
	at net.minecraft.class_1309.method_26827(class_1309.java:294)
	at net.minecraft.class_1308.method_26828(class_1308.java:158)
	at net.minecraft.class_7298.method_42655(class_7298.java:177)
	at net.minecraft.class_5135.<clinit>(class_5135.java:84)
	at net.minecraft.class_2966.method_17598(class_2966.java:136)
	at net.minecraft.client.main.Main.method_44604(Main.java:162)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.ClassNotFoundException: io.github.tropheusj.serialization_hooks.ingredient.IngredientDeserializer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more
```

Need to add:
`serialization_hooks_version=0.3.24`
`modImplementation(include("io.github.tropheusj:serialization-hooks:${project.serialization_hooks_version}"))`

**Comment by TheWinABagel** [comment]
Looks like this is cause you have an old version of porting lib from somewhere else, porting lib includes that library by default in newer versions.
