### ISSUE TITLE
Shearing Sheep Via Dispenser Crashes Game/Server Due to Zenith

### ISSUE THREAD

**Issue by BlazeWarfaree** [TheWinABagel/Zenith#73]
Here is a link to my crash log, it makes references to zenith in the crash log https://mclo.gs/Qqh9d0h

 [10:53:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.crash.CrashException: Exception ticking world
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:901) ~[client-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:824) ~[client-intermediary.jar:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:105) ~[client-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[client-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.item.ItemStack.getItem()" because "stack" is null
    at net.minecraft.enchantment.EnchantmentHelper.handler$gac000$indrev$customEnchantProvider(EnchantmentHelper.java:4021) ~[client-intermediary.jar:?]
    at net.minecraft.enchantment.EnchantmentHelper.getLevel(EnchantmentHelper.java) ~[client-intermediary.jar:?]
    at net.minecraft.entity.passive.SheepEntity.redirect$okp000$zenith$bleh(SheepEntity.java:2043) ~[client-intermediary.jar:?]
    at net.minecraft.entity.passive.SheepEntity.sheared(SheepEntity.java:235) ~[client-intermediary.jar:?]
    at net.minecraft.block.dispenser.ShearsDispenserBehavior.tryShearEntity(ShearsDispenserBehavior.java:61) ~[client-intermediary.jar:?]
    at net.minecraft.block.dispenser.ShearsDispenserBehavior.dispenseSilently(ShearsDispenserBehavior.java:29) ~[client-intermediary.jar:?]
    at net.minecraft.block.dispenser.ItemDispenserBehavior.dispense(ItemDispenserBehavior.java:16) ~[client-intermediary.jar:?]
    at net.minecraft.block.DispenserBlock.dispense(DispenserBlock.java:90) ~[client-intermediary.jar:?]
    at net.minecraft.block.DispenserBlock.scheduledTick(DispenserBlock.java:113) ~[client-intermediary.jar:?]
    at net.minecraft.block.AbstractBlock$AbstractBlockState.scheduledTick(AbstractBlock.java:1113) ~[client-intermediary.jar:?]
    at net.minecraft.server.world.ServerWorld.tickBlock(ServerWorld.java:728) ~[client-intermediary.jar:?]
    at net.minecraft.world.tick.WorldTickScheduler.tick(WorldTickScheduler.java:215) ~[client-intermediary.jar:?]
    at net.minecraft.world.tick.WorldTickScheduler.tick(WorldTickScheduler.java:98) ~[client-intermediary.jar:?]
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:323) ~[client-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:897) ~[client-intermediary.jar:?]
    ... 5 more
[10:53:51] [Server thread/WARN]: Suppressing EXPERIMENTAL level lifecycle

**Comment by TheWinABagel** [comment]
Will be fixed in 0.2.1

**Comment by TheWinABagel** [comment]
Fixed with 0.2.1
